.PHONY: clean All

All:
	@echo "----------Building project:[ Ex_10 - Release ]----------"
	@cd "Ex_10" && "$(MAKE)" -f  "Ex_10.mk"
clean:
	@echo "----------Cleaning project:[ Ex_10 - Release ]----------"
	@cd "Ex_10" && "$(MAKE)" -f  "Ex_10.mk" clean
